### PR TITLE
replace 'old' font-awesome files with newer ones

### PR DESCRIPTION
**Pull request by Ruud68**
Hi, change long due :)
Was missing icons like fa-at and fa-whatsapp. Troubleshooting learned that these where not in the old version shipped with meet_gavern.
This PR holds font-awesome version 4.5.0 bringing it up to par again :)
Hope this helps!

### CODE REVIEW

**Comment by dziudek** [comment]
This is a breaking change as Font Awesome 3.* uses different classes than 4.* and it will destroy the whole demo content and websites which uses old icons.

**Comment by Ruud68** [comment]
shoot :(
I don't see anything breaking on my websites. Maybe I am looking at the wrong things or I am not using it. Current problem is with plugin that uses font-awesome for displaying eg whatsapp button > this is not showing as fa-whatsapp is not present in v3.2.1 (same for email icon > fa-at)

**Comment by dziudek** [comment]
There is no problem to use it on your website, but I cannot accept this change in a template which can break the page for other users :) Old font awesome uses syntax like **icon-x** when new font awesome uses syntax like **fa fa-x**

**Comment by Ruud68** [comment]
Okay, thanks for the info :) Not using meet_gavern to its full extend on my websites so not running into any issues.
If more people are requesting new font-awesome version it would make sense to do a 'search & replace' on the code. But this will involve a lot of work and testing :(
So better to just keep this a 'local' change.

**Pull request closed without merging**
